using System;

public class LKeys
{
	public const string RUNE_NAME_GLACIER = "RUNE_NAME_GLACIER";

	public const string RUNE_DESC_GLACIER = "RUNE_DESC_GLACIER";

	public const string RUNE_NAME_BLEAK = "RUNE_NAME_BLEAK";

	public const string RUNE_DESC_BLEAK = "RUNE_DESC_BLEAK";

	public const string RUNE_NAME_LUMINOSITY = "RUNE_NAME_LUMINOSITY";

	public const string RUNE_DESC_LUMINOSITY = "RUNE_DESC_LUMINOSITY";

	public const string RUNE_NAME_BLAZE = "RUNE_NAME_BLAZE";

	public const string RUNE_DESC_BLAZE = "RUNE_DESC_BLAZE";

	public const string RUNE_NAME_DISCHARGE = "RUNE_NAME_DISCHARGE";

	public const string RUNE_DESC_DISCHARGE = "RUNE_DESC_DISCHARGE";

	public const string RUNE_NAME_RASH = "RUNE_NAME_RASH";

	public const string RUNE_DESC_RASH = "RUNE_DESC_RASH";

	public const string RUNE_NAME_STINGER = "RUNE_NAME_STINGER";

	public const string RUNE_DESC_STINGER = "RUNE_DESC_STINGER";

	public const string RUNE_NAME_HOTWAVE = "RUNE_NAME_HOTWAVE";

	public const string RUNE_DESC_HOTWAVE = "RUNE_DESC_HOTWAVE";

	public const string HERO_NAME_HILT = "HERO_NAME_HILT";

	public const string HERO_NAME_BELLYLARF = "HERO_NAME_BELLYLARF";

	public const string HERO_NAME_VEXX = "HERO_NAME_VEXX";

	public const string HERO_NAME_V = "HERO_NAME_V";

	public const string HERO_NAME_KIND_LENNY = "HERO_NAME_KIND_LENNY";

	public const string HERO_NAME_WENDLE = "HERO_NAME_WENDLE";

	public const string HERO_NAME_BOOMER_BADLAD = "HERO_NAME_BOOMER_BADLAD";

	public const string HERO_NAME_SAM = "HERO_NAME_SAM";

	public const string HERO_NAME_LIA = "HERO_NAME_LIA";

	public const string HERO_NAME_JIM = "HERO_NAME_HANDSUM_JIM";

	public const string HERO_NAME_TAM = "HERO_NAME_TAM";

	public const string HERO_NAME_WARLOCK = "HERO_NAME_WARLOCK";

	public const string HERO_NAME_GOBLIN = "HERO_NAME_GOBLIN";

	public const string HERO_NAME_BABU = "HERO_NAME_BABU";

	public const string HERO_NAME_RON = "HERO_NAME_RON";

	public const string HERO_DESC_HILT = "HERO_DESC_HILT";

	public const string HERO_DESC_BELLYLARF = "HERO_DESC_BELLYLARF";

	public const string HERO_DESC_VEXX = "HERO_DESC_VEXX";

	public const string HERO_DESC_V = "HERO_DESC_V";

	public const string HERO_DESC_KIND_LENNY = "HERO_DESC_KIND_LENNY";

	public const string HERO_DESC_WENDLE = "HERO_DESC_WENDLE";

	public const string HERO_DESC_BOOMER_BADLAD = "HERO_DESC_BOOMER_BADLAD";

	public const string HERO_DESC_SAM = "HERO_DESC_SAM";

	public const string HERO_DESC_LIA = "HERO_DESC_LIA";

	public const string HERO_DESC_JIM = "HERO_DESC_HANDSUM_JIM";

	public const string HERO_DESC_TAM = "HERO_DESC_TAM";

	public const string HERO_DESC_WARLOCK = "HERO_DESC_WARLOCK";

	public const string HERO_DESC_GOBLIN = "HERO_DESC_GOBLIN";

	public const string HERO_DESC_BABU = "HERO_DESC_BABU";

	public const string HERO_DESC_RON = "HERO_DESC_RON";

	public const string ITEM_NAME_SLAP_GLOVES = "ITEM_NAME_SLAP_GLOVES";

	public const string ITEM_NAME_HARMBURGER = "ITEM_NAME_HARMBURGER";

	public const string ITEM_NAME_LETTER_OPENER = "ITEM_NAME_LETTER_OPENER";

	public const string ITEM_NAME_SHINY_HELMET = "ITEM_NAME_SHINY_HELMET";

	public const string ITEM_NAME_LEG_OF_BEEF = "ITEM_NAME_LEG_OF_BEEF";

	public const string ITEM_NAME_MORNING_STAR = "ITEM_NAME_MORNING_STAR";

	public const string ITEM_NAME_GOLDEN_CROWN = "ITEM_NAME_GOLDEN_CROWN";

	public const string ITEM_NAME_IRRESISTIBLE_CAKE = "ITEM_NAME_IRRESISTIBLE_CAKE";

	public const string ITEM_NAME_BELT_OF_MIGHT = "ITEM_NAME_BELT_OF_MIGHT";

	public const string ITEM_NAME_GOLDEN_APPLE = "ITEM_NAME_GOLDEN_APPLE";

	public const string ITEM_NAME_COOKED_CHICKEN = "ITEM_NAME_COOKED_CHICKEN";

	public const string ITEM_NAME_POCKET_CANNON = "ITEM_NAME_POCKET_CANNON";

	public const string ITEM_NAME_BOOK_OF_ECONOMICS = "ITEM_NAME_BOOK_OF_ECONOMICS";

	public const string ITEM_NAME_ELIXIR_OF_VITALITY = "ITEM_NAME_ELIXIR_OF_VITALITY";

	public const string ITEM_NAME_SCROLL_OF_DARKNESS = "ITEM_NAME_SCROLL_OF_DARKNESS";

	public const string ITEM_NAME_GOLD_SACK = "ITEM_NAME_GOLD_SACK";

	public const string ITEM_NAME_HEALTH_TRAP = "ITEM_NAME_HEALTH_TRAP";

	public const string ITEM_NAME_POISONED_DAGGER = "ITEM_NAME_POISONED_DAGGER";

	public const string ITEM_NAME_PIGGY_BANK = "ITEM_NAME_PIGGY_BANK";

	public const string ITEM_NAME_WILDFIRE_POTION = "ITEM_NAME_WILDFIRE_POTION";

	public const string ITEM_NAME_SHORT_FUSED_BOMB = "ITEM_NAME_SHORT_FUSED_BOMB";

	public const string ITEM_NAME_GOLDEN_BRACER = "ITEM_NAME_GOLDEN_BRACER";

	public const string ITEM_NAME_SPIT_POT = "ITEM_NAME_SPIT_POT";

	public const string ITEM_NAME_AXE_OF_REVENGE = "ITEM_NAME_AXE_OF_REVENGE";

	public const string ITEM_NAME_GOLDEN_FRAME = "ITEM_NAME_GOLDEN_FRAME";

	public const string ITEM_NAME_FISH_OIL = "ITEM_NAME_FISH_OIL";

	public const string ITEM_NAME_TARGET_DUMMY = "ITEM_NAME_TARGET_DUMMY";

	public const string ITEM_NAME_PEIXOTOS_GUITAR = "ITEM_NAME_PEIXOTOS_GUITAR";

	public const string ITEM_NAME_PANS_FLUTE = "ITEM_NAME_PANS_FLUTE";

	public const string ITEM_NAME_JACKS_MASK = "ITEM_NAME_JACKS_MASK";

	public const string ITEM_NAME_GOLDEN_FEATHER = "ITEM_NAME_GOLDEN_FEATHER";

	public const string ITEM_NAME_JUICY_MEAT = "ITEM_NAME_JUICY_MEAT";

	public const string ITEM_NAME_DEADLY_SHELLS = "ITEM_NAME_DEADLY_SHELLS";

	public const string ITEM_NAME_GOLDEN_KEY = "ITEM_NAME_GOLDEN_KEY";

	public const string ITEM_NAME_SPARE_LEG = "ITEM_NAME_SPARE_LEG";

	public const string ITEM_NAME_SPY_LENS = "ITEM_NAME_SPY_LENS";

	public const string ITEM_NAME_FRIENDLY_SKULL = "ITEM_NAME_FRIENDLY_SKULL";

	public const string ITEM_NAME_GOLD_AMULET = "ITEM_NAME_GOLD_AMULET";

	public const string ITEM_NAME_VILE_OF_VILENESS = "ITEM_NAME_VILE_OF_VILENESS";

	public const string ITEM_NAME_SENSIBLE_SHOES = "ITEM_NAME_SENSIBLE_SHOES";

	public const string ITEM_NAME_HERILOOM_SPICES = "ITEM_NAME_HERILOOM_SPICES";

	public const string ITEM_NAME_FAVORITE_TEA_CUP = "ITEM_NAME_FAVORITE_TEA_CUP";

	public const string ITEM_NAME_JEWLED_CLAW = "ITEM_NAME_JEWLED_CLAW";

	public const string ITEM_NAME_BARELY_USED_TOY = "ITEM_NAME_BARELY_USED_TOY";

	public const string ITEM_NAME_CRITTER_KIBBLE = "ITEM_NAME_CRITTER_KIBBLE";

	public const string SKILL_NAME_DEADLY_TWIRL = "SKILL_NAME_DEADLY_TWIRL";

	public const string SKILL_DESC_DEADLY_TWIRL = "SKILL_DESC_DEADLY_TWIRL";

	public const string SKILL_NAME_I_HAVE_THE_POWER = "SKILL_NAME_I_HAVE_THE_POWER";

	public const string SKILL_DESC_I_HAVE_THE_POWER = "SKILL_DESC_I_HAVE_THE_POWER";

	public const string SKILL_NAME_DODGE = "SKILL_NAME_DODGE";

	public const string SKILL_DESC_DODGE = "SKILL_DESC_DODGE";

	public const string SKILL_NAME_FOREST_SON = "SKILL_NAME_FOREST_SON";

	public const string SKILL_DESC_FOREST_SON = "SKILL_DESC_FOREST_SON";

	public const string SKILL_NAME_PARANOIA = "SKILL_NAME_PARANOIA";

	public const string SKILL_DESC_PARANOIA = "SKILL_DESC_PARANOIA";

	public const string SKILL_NAME_EVERLAST = "SKILL_NAME_EVERLAST";

	public const string SKILL_DESC_EVERLAST = "SKILL_DESC_EVERLAST";

	public const string SKILL_NAME_REVERSED_EXCALIBUR = "SKILL_NAME_REVERSED_EXCALIBUR";

	public const string SKILL_DESC_REVERSED_EXCALIBUR = "SKILL_DESC_REVERSED_EXCALIBUR";

	public const string SKILL_NAME_LUCKY_BOY = "SKILL_NAME_LUCKY_BOY";

	public const string SKILL_DESC_LUCKY_BOY = "SKILL_DESC_LUCKY_BOY";

	public const string SKILL_NAME_FRIENDSHIP = "SKILL_NAME_FRIENDSHIP";

	public const string SKILL_DESC_FRIENDSHIP = "SKILL_DESC_FRIENDSHIP";

	public const string SKILL_NAME_SHARP_EDGE = "SKILL_NAME_SHARP_EDGE";

	public const string SKILL_DESC_SHARP_EDGE = "SKILL_DESC_SHARP_EDGE";

	public const string SKILL_NAME_SON_OF_THE_WIND = "SKILL_NAME_SON_OF_THE_WIND";

	public const string SKILL_DESC_SON_OF_THE_WIND = "SKILL_DESC_SON_OF_THE_WIND";

	public const string SKILL_NAME_ANGER = "SKILL_NAME_ANGER";

	public const string SKILL_DESC_ANGER = "SKILL_DESC_ANGER";

	public const string SKILL_NAME_TAUNT = "SKILL_NAME_TAUNT";

	public const string SKILL_DESC_TAUNT = "SKILL_DESC_TAUNT";

	public const string SKILL_NAME_BIG_GUY = "SKILL_NAME_BIG_GUY";

	public const string SKILL_DESC_BIG_GUY = "SKILL_DESC_BIG_GUY";

	public const string SKILL_NAME_BASH = "SKILL_NAME_BASH";

	public const string SKILL_DESC_BASH = "SKILL_DESC_BASH";

	public const string SKILL_NAME_RESILIENCE = "SKILL_NAME_RESILIENCE";

	public const string SKILL_DESC_RESILIENCE = "SKILL_DESC_RESILIENCE";

	public const string SKILL_NAME_ANGER_MANAGEMENT = "SKILL_NAME_ANGER_MANAGEMENT";

	public const string SKILL_DESC_ANGER_MANAGEMENT = "SKILL_DESC_ANGER_MANAGEMENT";

	public const string SKILL_NAME_LUNCH_TIME = "SKILL_NAME_LUNCH_TIME";

	public const string SKILL_DESC_LUNCH_TIME = "SKILL_DESC_LUNCH_TIME";

	public const string SKILL_NAME_TOUGHNESS = "SKILL_NAME_TOUGHNESS";

	public const string SKILL_DESC_TOUGHNESS = "SKILL_DESC_TOUGHNESS";

	public const string SKILL_NAME_FRESH_MEAT = "SKILL_NAME_FRESH_MEAT";

	public const string SKILL_DESC_FRESH_MEAT = "SKILL_DESC_FRESH_MEAT";

	public const string SKILL_NAME_FULL_STOMACH = "SKILL_NAME_FULL_STOMACH";

	public const string SKILL_DESC_FULL_STOMACH = "SKILL_DESC_FULL_STOMACH";

	public const string SKILL_NAME_REGENERATION = "SKILL_NAME_REGENERATION";

	public const string SKILL_DESC_REGENERATION = "SKILL_DESC_REGENERATION";

	public const string SKILL_NAME_SHOCK_WAVE = "SKILL_NAME_SHOCK_WAVE";

	public const string SKILL_DESC_SHOCK_WAVE = "SKILL_DESC_SHOCK_WAVE";

	public const string SKILL_NAME_CONCENTRATION = "SKILL_NAME_CONCENTRATION";

	public const string SKILL_DESC_CONCENTRATION = "SKILL_DESC_CONCENTRATION";

	public const string SKILL_NAME_MAD_GIRL = "SKILL_NAME_MAD_GIRL";

	public const string SKILL_DESC_MAD_GIRL = "SKILL_DESC_MAD_GIRL";

	public const string SKILL_NAME_VILLAGE_GIRL = "SKILL_NAME_VILLAGE_GIRL";

	public const string SKILL_DESC_VILLAGE_GIRL = "SKILL_DESC_VILLAGE_GIRL";

	public const string SKILL_NAME_RECYCLE = "SKILL_NAME_RECYCLE";

	public const string SKILL_DESC_RECYCLE = "SKILL_DESC_RECYCLE";

	public const string SKILL_NAME_COLLECT_SCRAPS = "SKILL_NAME_COLLECT_SCRAPS";

	public const string SKILL_DESC_COLLECT_SCRAPS = "SKILL_DESC_COLLECT_SCRAPS";

	public const string SKILL_NAME_FAST_AND_CHEERFUL = "SKILL_NAME_FAST_AND_CHEERFUL";

	public const string SKILL_DESC_FAST_AND_CHEERFUL = "SKILL_DESC_FAST_AND_CHEERFUL";

	public const string SKILL_NAME_HARD_TRAINING = "SKILL_NAME_HARD_TRAINING";

	public const string SKILL_DESC_HARD_TRAINING = "SKILL_DESC_HARD_TRAINING";

	public const string SKILL_NAME_CHILL_DOWN = "SKILL_NAME_CHILL_DOWN";

	public const string SKILL_DESC_CHILL_DOWN = "SKILL_DESC_CHILL_DOWN";

	public const string SKILL_NAME_FORGE = "SKILL_NAME_FORGE";

	public const string SKILL_DESC_FORGE = "SKILL_DESC_FORGE";

	public const string SKILL_NAME_EARTHQUAKE = "SKILL_NAME_EARTHQUAKE";

	public const string SKILL_DESC_EARTHQUAKE = "SKILL_DESC_EARTHQUAKE";

	public const string SKILL_NAME_MINI_CANNON = "SKILL_NAME_MINI_CANNON";

	public const string SKILL_DESC_MINI_CANNON = "SKILL_DESC_MINI_CANNON";

	public const string SKILL_NAME_BOMBARD = "SKILL_NAME_BOMBARD";

	public const string SKILL_DESC_BOMBARD = "SKILL_DESC_BOMBARD";

	public const string SKILL_NAME_XXL = "SKILL_NAME_XXL";

	public const string SKILL_DESC_XXL = "SKILL_DESC_XXL";

	public const string SKILL_NAME_ROTTEN_APPLE = "SKILL_NAME_ROTTEN_APPLE";

	public const string SKILL_DESC_ROTTEN_APPLE = "SKILL_DESC_ROTTEN_APPLE";

	public const string SKILL_NAME_CONSTITUTION = "SKILL_NAME_CONSTITUTION";

	public const string SKILL_DESC_CONSTITUTION = "SKILL_DESC_CONSTITUTION";

	public const string SKILL_NAME_WELL_FED = "SKILL_NAME_WELL_FED";

	public const string SKILL_DESC_WELL_FED = "SKILL_DESC_WELL_FED";

	public const string SKILL_NAME_EAT_AN_APPLE = "SKILL_NAME_EAT_AN_APPLE";

	public const string SKILL_DESC_EAT_AN_APPLE = "SKILL_DESC_EAT_AN_APPLE";

	public const string SKILL_NAME_SHARP_SHOOTER = "SKILL_NAME_SHARP_SHOOTER";

	public const string SKILL_DESC_SHARP_SHOOTER = "SKILL_DESC_SHARP_SHOOTER";

	public const string SKILL_NAME_FAST_RELOADER = "SKILL_NAME_FAST_RELOADER";

	public const string SKILL_DESC_FAST_RELOADER = "SKILL_DESC_FAST_RELOADER";

	public const string SKILL_DESC_FULL_FAST_RELOADER = "SKILL_DESC_FULL_FAST_RELOADER";

	public const string SKILL_NAME_BIG_STOMACH = "SKILL_NAME_BIG_STOMACH";

	public const string SKILL_DESC_BIG_STOMACH = "SKILL_DESC_BIG_STOMACH";

	public const string SKILL_NAME_NICEST_KILLER = "SKILL_NAME_NICEST_KILLER";

	public const string SKILL_DESC_NICEST_KILLER = "SKILL_DESC_NICEST_KILLER";

	public const string SKILL_NAME_LOB_THE_MAGIC = "SKILL_NAME_LOB_THE_MAGIC";

	public const string SKILL_DESC_LOB_THE_MAGIC = "SKILL_DESC_LOB_THE_MAGIC";

	public const string SKILL_NAME_OUT_OF_CONTROL = "SKILL_NAME_OUT_OF_CONTROL";

	public const string SKILL_DESC_OUT_OF_CONTROL = "SKILL_DESC_OUT_OF_CONTROL";

	public const string SKILL_NAME_TRICKS = "SKILL_NAME_TRICKS";

	public const string SKILL_DESC_TRICKS = "SKILL_DESC_TRICKS";

	public const string SKILL_NAME_FORGETFUL = "SKILL_NAME_FORGETFUL";

	public const string SKILL_DESC_FORGETFUL = "SKILL_DESC_FORGETFUL";

	public const string SKILL_NAME_CRAZINESS = "SKILL_NAME_CRAZINESS";

	public const string SKILL_DESC_CRAZINESS = "SKILL_DESC_CRAZINESS";

	public const string SKILL_NAME_DOUBLE_MISSILE = "SKILL_NAME_DOUBLE_MISSILE";

	public const string SKILL_DESC_DOUBLE_MISSILE = "SKILL_DESC_DOUBLE_MISSILE";

	public const string SKILL_NAME_THUNDER_SOMETHING = "SKILL_NAME_THUNDER_SOMETHING";

	public const string SKILL_DESC_THUNDER_SOMETHING = "SKILL_DESC_THUNDER_SOMETHING";

	public const string SKILL_NAME_SPIRIT_TALK = "SKILL_NAME_SPIRIT_TALK";

	public const string SKILL_DESC_SPIRIT_TALK = "SKILL_DESC_SPIRIT_TALK";

	public const string SKILL_NAME_WISDOM = "SKILL_NAME_WISDOM";

	public const string SKILL_DESC_WISDOM = "SKILL_DESC_WISDOM";

	public const string SKILL_NAME_ELDERNESS = "SKILL_NAME_ELDERNESS";

	public const string SKILL_DESC_ELDERNESS = "SKILL_DESC_ELDERNESS";

	public const string SKILL_NAME_RAPID_THUNDER = "SKILL_NAME_RAPID_THUNDER";

	public const string SKILL_DESC_RAPID_THUNDER = "SKILL_DESC_RAPID_THUNDER";

	public const string SKILL_NAME_MASTER_THIEF = "SKILL_NAME_MASTER_THIEF";

	public const string SKILL_DESC_MASTER_THIEF = "SKILL_DESC_MASTER_THIEF";

	public const string SKILL_NAME_SLICE_AND_DICE = "SKILL_NAME_SLICE_AND_DICE";

	public const string SKILL_DESC_SLICE_AND_DICE = "SKILL_DESC_SLICE_AND_DICE";

	public const string SKILL_NAME_POISONED_DAGGERS = "SKILL_NAME_POISONED_DAGGERS";

	public const string SKILL_DESC_POISONED_DAGGERS = "SKILL_DESC_POISONED_DAGGERS";

	public const string SKILL_NAME_HIDDEN_DAGGERS = "SKILL_NAME_HIDDEN_DAGGERS";

	public const string SKILL_DESC_HIDDEN_DAGGERS = "SKILL_DESC_HIDDEN_DAGGERS";

	public const string SKILL_DESC_FULL_HIDDEN_DAGGERS = "SKILL_DESC_FULL_HIDDEN_DAGGERS";

	public const string SKILL_NAME_CITY_THIEF = "SKILL_NAME_CITY_THIEF";

	public const string SKILL_DESC_CITY_THIEF = "SKILL_DESC_CITY_THIEF";

	public const string SKILL_NAME_WEAK_POINT = "SKILL_NAME_WEAK_POINT";

	public const string SKILL_DESC_WEAK_POINT = "SKILL_DESC_WEAK_POINT";

	public const string SKILL_NAME_RUN_EMMET_RUN = "SKILL_NAME_RUN_EMMET_RUN";

	public const string SKILL_DESC_RUN_EMMET_RUN = "SKILL_DESC_RUN_EMMET_RUN";

	public const string SKILL_NAME_TREASURE_HUNTER = "SKILL_NAME_TREASURE_HUNTER";

	public const string SKILL_DESC_TREASURE_HUNTER = "SKILL_DESC_TREASURE_HUNTER";

	public const string SKILL_NAME_SWIFT_EMMET = "SKILL_NAME_SWIFT_EMMET";

	public const string SKILL_DESC_SWIFT_EMMET = "SKILL_DESC_SWIFT_EMMET";

	public const string SKILL_NAME_EVASION = "SKILL_NAME_EVASION";

	public const string SKILL_DESC_EVASION = "SKILL_DESC_EVASION";

	public const string SKILL_NAME_HEART_SEEKER = "SKILL_NAME_HEART_SEEKER";

	public const string SKILL_DESC_HEART_SEEKER = "SKILL_DESC_HEART_SEEKER";

	public const string SKILL_NAME_KAMIKAZE = "SKILL_NAME_KAMIKAZE";

	public const string SKILL_DESC_KAMIKAZE = "SKILL_DESC_KAMIKAZE";

	public const string SKILL_NAME_FIREWORKS = "SKILL_NAME_FIREWORKS";

	public const string SKILL_DESC_FIREWORKS = "SKILL_DESC_FIREWORKS";

	public const string SKILL_NAME_CONCUSSION = "SKILL_NAME_CONCUSSION";

	public const string SKILL_DESC_CONCUSSION = "SKILL_DESC_CONCUSSION";

	public const string SKILL_NAME_STUBBERNNESS = "SKILL_NAME_STUBBERNNESS";

	public const string SKILL_DESC_STUBBERNNESS = "SKILL_DESC_STUBBERNNESS";

	public const string SKILL_NAME_MADNESS = "SKILL_NAME_MADNESS";

	public const string SKILL_DESC_MADNESS = "SKILL_DESC_MADNESS";

	public const string SKILL_NAME_FUEL_THEM_UP = "SKILL_NAME_FUEL_THEM_UP";

	public const string SKILL_DESC_FUEL_THEM_UP = "SKILL_DESC_FUEL_THEM_UP";

	public const string SKILL_NAME_JOKES_ON_YOU = "SKILL_NAME_JOKES_ON_YOU";

	public const string SKILL_DESC_JOKES_ON_YOU = "SKILL_DESC_JOKES_ON_YOU";

	public const string SKILL_NAME_FRAGMENTATION = "SKILL_NAME_FRAGMENTATION";

	public const string SKILL_DESC_FRAGMENTATION = "SKILL_DESC_FRAGMENTATION";

	public const string SKILL_NAME_BUT_MAYBE = "SKILL_NAME_BUT_MAYBE";

	public const string SKILL_DESC_BUT_MAYBE = "SKILL_DESC_BUT_MAYBE";

	public const string SKILL_NAME_CRACK_SHOT = "SKILL_NAME_CRACK_SHOT";

	public const string SKILL_DESC_CRACK_SHOT = "SKILL_DESC_CRACK_SHOT";

	public const string SKILL_NAME_EXPLOSIVE_SHOTS = "SKILL_NAME_EXPLOSIVE_SHOTS";

	public const string SKILL_DESC_EXPLOSIVE_SHOTS = "SKILL_DESC_EXPLOSIVE_SHOTS";

	public const string SKILL_NAME_REVENGE = "SKILL_NAME_REVENGE";

	public const string SKILL_DESC_REVENGE = "SKILL_DESC_REVENGE";

	public const string SKILL_NAME_SHIELDEM_ALL = "SKILL_NAME_SHIELDEM_ALL";

	public const string SKILL_DESC_SHIELDEM_ALL = "SKILL_DESC_SHIELDEM_ALL";

	public const string SKILL_NAME_BLOCK = "SKILL_NAME_BLOCK";

	public const string SKILL_DESC_BLOCK = "SKILL_DESC_BLOCK";

	public const string SKILL_NAME_REPEL = "SKILL_NAME_REPEL";

	public const string SKILL_DESC_REPEL = "SKILL_DESC_REPEL";

	public const string SKILL_NAME_ARROGANT = "SKILL_NAME_ARROGANT";

	public const string SKILL_DESC_ARROGANT = "SKILL_DESC_ARROGANT";

	public const string SKILL_NAME_MASTER_SHIELDER = "SKILL_NAME_MASTER_SHIELDER";

	public const string SKILL_DESC_MASTER_SHIELDER = "SKILL_DESC_MASTER_SHIELDER";

	public const string SKILL_NAME_SLAM = "SKILL_NAME_SLAM";

	public const string SKILL_DESC_SLAM = "SKILL_DESC_SLAM";

	public const string SKILL_NAME_HILL_MAN = "SKILL_NAME_HILL_MAN";

	public const string SKILL_DESC_HILL_MAN = "SKILL_DESC_HILL_MAN";

	public const string SKILL_NAME_PUNISHMENT = "SKILL_NAME_PUNISHMENT";

	public const string SKILL_DESC_PUNISHMENT = "SKILL_DESC_PUNISHMENT";

	public const string SKILL_NAME_TRANSCENDENCE = "SKILL_NAME_TRANSCENDENCE";

	public const string SKILL_DESC_TRANSCENDENCE = "SKILL_DESC_TRANSCENDENCE";

	public const string SKILL_NAME_LET_THEM_COME = "SKILL_NAME_LET_THEM_COME";

	public const string SKILL_DESC_LET_THEM_COME = "SKILL_DESC_LET_THEM_COME";

	public const string SKILL_NAME_TARGET_PRACTICE = "SKILL_NAME_TARGET_PRACTICE";

	public const string SKILL_DESC_TARGET_PRACTICE = "SKILL_DESC_TARGET_PRACTICE";

	public const string SKILL_NAME_SNIPE = "SKILL_NAME_SNIPE";

	public const string SKILL_DESC_SNIPE = "SKILL_DESC_SNIPE";

	public const string SKILL_NAME_FEED_THE_POOR = "SKILL_NAME_FEED_THE_POOR";

	public const string SKILL_DESC_FEED_THE_POOR = "SKILL_DESC_FEED_THE_POOR";

	public const string SKILL_NAME_NOT_DEAF = "SKILL_NAME_NOT_DEAF";

	public const string SKILL_DESC_NOT_DEAF = "SKILL_DESC_NOT_DEAF";

	public const string SKILL_NAME_SURVIVALIST = "SKILL_NAME_SURVIVALIST";

	public const string SKILL_DESC_SURVIVALIST = "SKILL_DESC_SURVIVALIST";

	public const string SKILL_NAME_ONE_SHOT = "SKILL_NAME_ONE_SHOT";

	public const string SKILL_DESC_ONE_SHOT = "SKILL_DESC_ONE_SHOT";

	public const string SKILL_NAME_SWIFT_MOVES = "SKILL_NAME_SWIFT_MOVES";

	public const string SKILL_DESC_SWIFT_MOVES = "SKILL_DESC_SWIFT_MOVES";

	public const string SKILL_NAME_ACCURACY = "SKILL_NAME_ACCURACY";

	public const string SKILL_DESC_ACCURACY = "SKILL_DESC_ACCURACY";

	public const string SKILL_NAME_ELEGANCE = "SKILL_NAME_ELEGANCE";

	public const string SKILL_DESC_ELEGANCE = "SKILL_DESC_ELEGANCE";

	public const string SKILL_NAME_TRACKER = "SKILL_NAME_TRACKER";

	public const string SKILL_DESC_TRACKER = "SKILL_DESC_TRACKER";

	public const string SKILL_NAME_MULTI_SHOT = "SKILL_NAME_MULTI_SHOT";

	public const string SKILL_DESC_MULTI_SHOT = "SKILL_DESC_MULTI_SHOT";

	public const string SKILL_NAME_BITTERSWEET = "SKILL_NAME_BITTERSWEET";

	public const string SKILL_DESC_BITTERSWEET = "SKILL_DESC_BITTERSWEET";

	public const string SKILL_NAME_BATTLECRY = "SKILL_NAME_BATTLECRY";

	public const string SKILL_DESC_BATTLECRY = "SKILL_DESC_BATTLECRY";

	public const string SKILL_NAME_LULLABY = "SKILL_NAME_LULLABY";

	public const string SKILL_DESC_LULLABY = "SKILL_DESC_LULLABY";

	public const string SKILL_NAME_HEROISM = "SKILL_NAME_HEROISM";

	public const string SKILL_DESC_HEROISM = "SKILL_DESC_HEROISM";

	public const string SKILL_NAME_PARTY_TIME = "SKILL_NAME_PARTY_TIME";

	public const string SKILL_DESC_PARTY_TIME = "SKILL_DESC_PARTY_TIME";

	public const string SKILL_NAME_TOGETHER_WE_STAND = "SKILL_NAME_TOGETHER_WE_STAND";

	public const string SKILL_DESC_TOGETHER_WE_STAND = "SKILL_DESC_TOGETHER_WE_STAND";

	public const string SKILL_NAME_WEEPING_SONG = "SKILL_NAME_WEEPING_SONG";

	public const string SKILL_DESC_WEEPING_SONG = "SKILL_DESC_WEEPING_SONG";

	public const string SKILL_NAME_DEPRESSION = "SKILL_NAME_DEPRESSION";

	public const string SKILL_DESC_DEPRESSION = "SKILL_DESC_DEPRESSION";

	public const string SKILL_NAME_NOT_SO_FAST = "SKILL_NAME_NOT_SO_FAST";

	public const string SKILL_DESC_NOT_SO_FAST = "SKILL_DESC_NOT_SO_FAST";

	public const string SKILL_NAME_PRETTY_FACE = "SKILL_NAME_PRETTY_FACE";

	public const string SKILL_DESC_PRETTY_FACE = "SKILL_DESC_PRETTY_FACE";

	public const string SKILL_NAME_DIVIDED_WE_FALL = "SKILL_NAME_DIVIDED_WE_FALL";

	public const string SKILL_DESC_DIVIDED_WE_FALL = "SKILL_DESC_DIVIDED_WE_FALL";

	public const string SKILL_NAME_ROAR = "SKILL_NAME_ROAR";

	public const string SKILL_DESC_ROAR = "SKILL_DESC_ROAR";

	public const string SKILL_NAME_FLARE = "SKILL_NAME_FLARE";

	public const string SKILL_DESC_FLARE = "SKILL_DESC_FLARE";

	public const string SKILL_NAME_MARK = "SKILL_NAME_MARK";

	public const string SKILL_DESC_MARK = "SKILL_DESC_MARK";

	public const string SKILL_NAME_PREPERATION = "SKILL_NAME_PREPERATION";

	public const string SKILL_DESC_PREPERATION = "SKILL_DESC_PREPERATION";

	public const string SKILL_NAME_BANDAGE = "SKILL_NAME_BANDAGE";

	public const string SKILL_DESC_BANDAGE = "SKILL_DESC_BANDAGE";

	public const string SKILL_NAME_FEIGN_DEATH = "SKILL_NAME_FEIGN_DEATH";

	public const string SKILL_DESC_FEIGN_DEATH = "SKILL_DESC_FEIGN_DEATH";

	public const string SKILL_NAME_CROW_ATTACK = "SKILL_NAME_CROW_ATTACK";

	public const string SKILL_DESC_CROW_ATTACK = "SKILL_DESC_CROW_ATTACK";

	public const string SKILL_NAME_FRENZY = "SKILL_NAME_FRENZY";

	public const string SKILL_DESC_FRENZY = "SKILL_DESC_FRENZY";

	public const string SKILL_NAME_INSTINCTS = "SKILL_NAME_INSTINCTS";

	public const string SKILL_DESC_INSTINCTS = "SKILL_DESC_INSTINCTS";

	public const string SKILL_NAME_DEATH_FROM_ABOVE = "SKILL_NAME_DEATH_FROM_ABOVE";

	public const string SKILL_DESC_DEATH_FROM_ABOVE = "SKILL_DESC_DEATH_FROM_ABOVE";

	public const string SKILL_NAME_CALL_OF_WILD = "SKILL_NAME_CALL_OF_WILD";

	public const string SKILL_DESC_CALL_OF_WILD = "SKILL_DESC_CALL_OF_WILD";

	public const string SKILL_NAME_DARK_RITUAL = "SKILL_NAME_DARK_RITUAL";

	public const string SKILL_DESC_DARK_RITUAL = "SKILL_DESC_DARK_RITUAL";

	public const string SKILL_NAME_DEMONIC_SWARM = "SKILL_NAME_DEMONIC_SWARM";

	public const string SKILL_DESC_DEMONIC_SWARM = "SKILL_DESC_DEMONIC_SWARM";

	public const string SKILL_NAME_REGRET = "SKILL_NAME_REGRET";

	public const string SKILL_DESC_REGRET = "SKILL_DESC_REGRET";

	public const string SKILL_NAME_SOULSACRIFACE = "SKILL_NAME_SOULSACRIFACE";

	public const string SKILL_DESC_SOULSACRIFACE = "SKILL_DESC_SOULSACRIFACE";

	public const string SKILL_NAME_TASTEOFREVENGE = "SKILL_NAME_TASTEOFREVENGE";

	public const string SKILL_DESC_TASTEOFREVENGE = "SKILL_DESC_TASTEOFREVENGE";

	public const string SKILL_NAME_CHAKRA_BOOSTER = "SKILL_NAME_CHAKRA_BOOSTER";

	public const string SKILL_DESC_CHAKRA_BOOSTER = "SKILL_DESC_CHAKRA_BOOSTER";

	public const string SKILL_NAME_WARMER_SWARM = "SKILL_NAME_WARMER_SWARM";

	public const string SKILL_DESC_WARMER_SWARM = "SKILL_DESC_WARMER_SWARM";

	public const string SKILL_NAME_TERROR = "SKILL_NAME_TERROR";

	public const string SKILL_DESC_TERROR = "SKILL_DESC_TERROR";

	public const string SKILL_NAME_STRIKE_MIRROR = "SKILL_NAME_STRIKE_MIRROR";

	public const string SKILL_DESC_STRIKE_MIRROR = "SKILL_DESC_STRIKE_MIRROR";

	public const string SKILL_NAME_FEELSBETTER = "SKILL_NAME_FEELSBETTER";

	public const string SKILL_DESC_FEELSBETTER = "SKILL_DESC_FEELSBETTER";

	public const string SKILL_NAME_MY_PITTY_TEAM = "SKILL_NAME_MY_PITTY_TEAM";

	public const string SKILL_DESC_MY_PITTY_TEAM = "SKILL_DESC_MY_PITTY_TEAM";

	public const string SKILL_NAME_GREED_GRENADE = "SKILL_NAME_GREED_GRENADE";

	public const string SKILL_DESC_GREED_GRENADE = "SKILL_DESC_GREED_GRENADE";

	public const string SKILL_NAME_NEGOTIATE = "SKILL_NAME_NEGOTIATE";

	public const string SKILL_DESC_NEGOTIATE = "SKILL_DESC_NEGOTIATE";

	public const string SKILL_NAME_KEEN_NOSE = "SKILL_NAME_KEEN_NOSE";

	public const string SKILL_DESC_KEEN_NOSE = "SKILL_DESC_KEEN_NOSE";

	public const string SKILL_NAME_TRADE_SECRET = "SKILL_NAME_TRADE_SECRET";

	public const string SKILL_DESC_TRADE_SECRET = "SKILL_DESC_TRADE_SECRET";

	public const string SKILL_NAME_LOOSE_CHANGE = "SKILL_NAME_LOOSE_CHANGE";

	public const string SKILL_DESC_LOOSE_CHANGE = "SKILL_DESC_LOOSE_CHANGE";

	public const string SKILL_NAME_BARGAINER = "SKILL_NAME_BARGAINER";

	public const string SKILL_DESC_BARGAINER = "SKILL_DESC_BARGAINER";

	public const string SKILL_NAME_CONFUSING_PRESENCE = "SKILL_NAME_CONFUSING_PRESENCE";

	public const string SKILL_DESC_CONFUSING_PRESENCE = "SKILL_DESC_CONFUSING_PRESENCE";

	public const string SKILL_NAME_COMMON_AFFINITIES = "SKILL_NAME_COMMON_AFFINITIES";

	public const string SKILL_DESC_COMMON_AFFINITIES = "SKILL_DESC_COMMON_AFFINITIES";

	public const string SKILL_NAME_FORMER_FRIENDS = "SKILL_NAME_FORMER_FRIENDS";

	public const string SKILL_DESC_FORMER_FRIENDS = "SKILL_DESC_FORMER_FRIENDS";

	public const string SKILL_NAME_DISTRACTION = "SKILL_NAME_DISTRACTION";

	public const string SKILL_DESC_DISTRACTION = "SKILL_DESC_DISTRACTION";

	public const string SKILL_NAME_TIMIDFRIENDS = "SKILL_NAME_TIMIDFRIENDS";

	public const string SKILL_DESC_TIMIDFRIENDS = "SKILL_DESC_TIMIDFRIENDS";

	public const string SKILL_NAME_EASY_TARGETS = "SKILL_NAME_EASY_TARGETS";

	public const string SKILL_DESC_EASY_TARGETS = "SKILL_DESC_EASY_TARGETS";

	public const string SKILL_NAME_TAKE_ONE_FOR_THE_TEAM = "SKILL_NAME_TAKE_ONE_FOR_THE_TEAM";

	public const string SKILL_DESC_TAKE_ONE_FOR_THE_TEAM = "SKILL_DESC_TAKE_ONE_FOR_THE_TEAM";

	public const string SKILL_NAME_GOOD_CUP_OF_TEA = "SKILL_NAME_GOOD_CUP_OF_TEA";

	public const string SKILL_DESC_GOOD_CUP_OF_TEA = "SKILL_DESC_GOOD_CUP_OF_TEA";

	public const string SKILL_NAME_TOUGH_LOVE = "SKILL_NAME_TOUGH_LOVE";

	public const string SKILL_DESC_TOUGH_LOVE = "SKILL_DESC_TOUGH_LOVE";

	public const string SKILL_NAME_LONG_WINDED = "SKILL_NAME_LONG_WINDED";

	public const string SKILL_DESC_LONG_WINDED = "SKILL_DESC_LONG_WINDED";

	public const string SKILL_NAME_MORALE_BOOSTER = "SKILL_NAME_MORALE_BOOSTER";

	public const string SKILL_DESC_MORALE_BOOSTER = "SKILL_DESC_MORALE_BOOSTER";

	public const string SKILL_NAME_PARTICIPATION_TROPHY = "SKILL_NAME_PARTICIPATION_TROPHY";

	public const string SKILL_DESC_PARTICIPATION_TROPHY = "SKILL_DESC_PARTICIPATION_TROPHY";

	public const string SKILL_NAME_BRUSH_IT_OFF = "SKILL_NAME_BRUSH_IT_OFF";

	public const string SKILL_DESC_BRUSH_IT_OFF = "SKILL_DESC_BRUSH_IT_OFF";

	public const string SKILL_NAME_INNER_WORTH = "SKILL_NAME_INNER_WORTH";

	public const string SKILL_DESC_INNER_WORTH = "SKILL_DESC_INNER_WORTH";

	public const string SKILL_NAME_SHARE_THE_BURDEN = "SKILL_NAME_SHARE_THE_BURDEN";

	public const string SKILL_DESC_SHARE_THE_BURDEN = "SKILL_DESC_SHARE_THE_BURDEN";

	public const string SKILL_NAME_GOT_YOUR_BACK = "SKILL_NAME_GOT_YOUR_BACK";

	public const string SKILL_DESC_GOT_YOUR_BACK = "SKILL_DESC_GOT_YOUR_BACK";

	public const string SKILL_NAME_EXPERT_LOVE_LORE = "SKILL_NAME_EXPERT_LOVE_LORE";

	public const string SKILL_DESC_EXPERT_LOVE_LORE = "SKILL_DESC_EXPERT_LOVE_LORE";

	public const string SKILL_NAME_BEAST_MODE = "SKILL_NAME_BEAST_MODE";

	public const string SKILL_DESC_BEAST_MODE = "SKILL_DESC_BEAST_MODE";

	public const string SKILL_NAME_STAMPEDE = "SKILL_NAME_STAMPEDE";

	public const string SKILL_DESC_STAMPEDE = "SKILL_DESC_STAMPEDE";

	public const string SKILL_NAME_STRENGTH_IN_NUMBERS = "SKILL_NAME_STRENGTH_IN_NUMBERS";

	public const string SKILL_DESC_STRENGTH_IN_NUMBERS = "SKILL_DESC_STRENGTH_IN_NUMBERS";

	public const string SKILL_NAME_MASSIVE_PAWS = "SKILL_NAME_MASSIVE_PAWS";

	public const string SKILL_DESC_MASSIVE_PAWS = "SKILL_DESC_MASSIVE_PAWS";

	public const string SKILL_NAME_GO_FOR_THE_EYES = "SKILL_NAME_GO_FOR_THE_EYES";

	public const string SKILL_DESC_GO_FOR_THE_EYES = "SKILL_DESC_GO_FOR_THE_EYES";

	public const string SKILL_NAME_IMPULSIVE = "SKILL_NAME_IMPULSIVE";

	public const string SKILL_DESC_IMPULSIVE = "SKILL_DESC_IMPULSIVE";

	public const string SKILL_NAME_LARRY = "SKILL_NAME_LARRY";

	public const string SKILL_DESC_LARRY = "SKILL_DESC_LARRY";

	public const string SKILL_NAME_HUNTER_INSTINCT = "SKILL_NAME_HUNTER_INSTINCT";

	public const string SKILL_DESC_HUNTER_INSTINCT = "SKILL_DESC_HUNTER_INSTINCT";

	public const string SKILL_NAME_CURLY = "SKILL_NAME_CURLY";

	public const string SKILL_DESC_CURLY = "SKILL_DESC_CURLY";

	public const string SKILL_NAME_MOE = "SKILL_NAME_MOE";

	public const string SKILL_DESC_MOE = "SKILL_DESC_MOE";

	public const string SKILL_NAME_RAGE_DRIVEN = "SKILL_NAME_RAGE_DRIVEN";

	public const string SKILL_DESC_RAGE_DRIVEN = "SKILL_DESC_RAGE_DRIVEN";

	public const string SKILL_COOLDOWN = "SKILL_COOLDOWN";

	public const string RING_NAME_LIGHTNING = "RING_NAME_LIGHTNING";

	public const string RING_DESC_LIGHTNING = "RING_DESC_LIGHTNING";

	public const string RING_SPECIAL_LIGHTNING = "RING_SPECIAL_LIGHTNING";

	public const string RUNE_NAME_CHARGE = "RUNE_NAME_CHARGE";

	public const string RUNE_DESC_CHARGE = "RUNE_DESC_CHARGE";

	public const string RUNE_NAME_BOUNCE = "RUNE_NAME_BOUNCE";

	public const string RUNE_DESC_BOUNCE = "RUNE_DESC_BOUNCE";

	public const string RUNE_NAME_SHOCK = "RUNE_NAME_SHOCK";

	public const string RUNE_DESC_SHOCK = "RUNE_DESC_SHOCK";

	public const string RUNE_NAME_ZAP = "RUNE_NAME_ZAP";

	public const string RUNE_DESC_ZAP = "RUNE_DESC_ZAP";

	public const string RUNE_NAME_OVERLOAD = "RUNE_NAME_OVERLOAD";

	public const string RUNE_DESC_OVERLOAD = "RUNE_DESC_OVERLOAD";

	public const string RUNE_NAME_THUNDER = "RUNE_NAME_THUNDER";

	public const string RUNE_DESC_THUNDER = "RUNE_DESC_THUNDER";

	public const string RUNE_NAME_ENERGY = "RUNE_NAME_ENERGY";

	public const string RUNE_DESC_ENERGY = "RUNE_DESC_ENERGY";

	public const string RUNE_NAME_DAZE = "RUNE_NAME_DAZE";

	public const string RUNE_DESC_DAZE = "RUNE_DESC_DAZE";

	public const string RING_NAME_ICE = "RING_NAME_ICE";

	public const string RING_DESC_ICE = "RING_DESC_ICE";

	public const string RING_SPECIAL_ICE = "RING_SPECIAL_ICE";

	public const string RUNE_NAME_BLESSING = "RUNE_NAME_BLESSING";

	public const string RUNE_DESC_BLESSING = "RUNE_DESC_BLESSING";

	public const string RUNE_NAME_SHARPNESS = "RUNE_NAME_SHARPNESS";

	public const string RUNE_DESC_SHARPNESS = "RUNE_DESC_SHARPNESS";

	public const string RUNE_NAME_COLD_WIND = "RUNE_NAME_COLD_WIND";

	public const string RUNE_DESC_COLD_WIND = "RUNE_DESC_COLD_WIND";

	public const string RUNE_NAME_ICE_BLAST = "RUNE_NAME_ICE_BLAST";

	public const string RUNE_DESC_ICE_BLAST = "RUNE_DESC_ICE_BLAST";

	public const string RUNE_NAME_STORMER = "RUNE_NAME_STORMER";

	public const string RUNE_DESC_STORMER = "RUNE_DESC_STORMER";

	public const string RUNE_NAME_ICE_RAGE = "RUNE_NAME_ICE_RAGE";

	public const string RUNE_DESC_ICE_RAGE = "RUNE_DESC_ICE_RAGE";

	public const string RUNE_NAME_NOVA = "RUNE_NAME_NOVA";

	public const string RUNE_DESC_NOVA = "RUNE_DESC_NOVA";

	public const string RUNE_NAME_SHATTER = "RUNE_NAME_SHATTER";

	public const string RUNE_DESC_SHATTER = "RUNE_DESC_SHATTER";

	public const string RING_NAME_FIRE = "RING_NAME_FIRE";

	public const string RING_DESC_FIRE = "RING_DESC_FIRE";

	public const string RING_SPECIAL_FIRE = "RING_SPECIAL_FIRE";

	public const string RUNE_NAME_IGNITION = "RUNE_NAME_IGNITION";

	public const string RUNE_DESC_IGNITION = "RUNE_DESC_IGNITION";

	public const string RUNE_NAME_FIRE_RESISTANCE = "RUNE_NAME_FIRE_RESISTANCE";

	public const string RUNE_DESC_FIRE_RESISTANCE = "RUNE_DESC_FIRE_RESISTANCE";

	public const string RUNE_NAME_COOLER = "RUNE_NAME_COOLER";

	public const string RUNE_DESC_COOLER = "RUNE_DESC_COOLER";

	public const string RUNE_NAME_INNER_FIRE = "RUNE_NAME_INNER_FIRE";

	public const string RUNE_DESC_INNER_FIRE = "RUNE_DESC_INNER_FIRE";

	public const string RUNE_NAME_ENCHANTED_FIRE = "RUNE_NAME_ENCHANTED_FIRE";

	public const string RUNE_DESC_ENCHANTED_FIRE = "RUNE_DESC_ENCHANTED_FIRE";

	public const string RUNE_NAME_MELTDOWN = "RUNE_NAME_MELTDOWN";

	public const string RUNE_DESC_MELTDOWN = "RUNE_DESC_MELTDOWN";

	public const string RUNE_NAME_MAGMA = "RUNE_NAME_MAGMA";

	public const string RUNE_DESC_MAGMA = "RUNE_DESC_MAGMA";

	public const string RUNE_NAME_EXPLOSIVE = "RUNE_NAME_EXPLOSIVE";

	public const string RUNE_DESC_EXPLOSIVE = "RUNE_DESC_EXPLOSIVE";

	public const string RING_NAME_EARTH = "RING_NAME_EARTH";

	public const string RING_SPECIAL_EARTH = "RING_SPECIAL_EARTH";

	public const string RING_DESC_EARTH = "RING_DESC_EARTH";

	public const string RUNE_NAME_METEORITE = "RUNE_NAME_METEORITE";

	public const string RUNE_DESC_METEORITE = "RUNE_DESC_METEORITE";

	public const string RUNE_NAME_SPIRITUAL = "RUNE_NAME_SPIRITUAL";

	public const string RUNE_DESC_SPIRITUAL = "RUNE_DESC_SPIRITUAL";

	public const string RUNE_NAME_STARFALL = "RUNE_NAME_STARFALL";

	public const string RUNE_DESC_STARFALL = "RUNE_DESC_STARFALL";

	public const string RUNE_NAME_ENCHANT = "RUNE_NAME_ENCHANT";

	public const string RUNE_DESC_ENCHANT = "RUNE_DESC_ENCHANT";

	public const string RUNE_NAME_RECYCLE = "RUNE_NAME_RECYCLE";

	public const string RUNE_DESC_RECYCLE = "RUNE_DESC_RECYCLE";

	public const string RUNE_NAME_REMNANTS = "RUNE_NAME_REMNANTS";

	public const string RUNE_DESC_REMNANTS = "RUNE_DESC_REMNANTS";

	public const string RUNE_NAME_SMASH = "RUNE_NAME_SMASH";

	public const string RUNE_DESC_SMASH = "RUNE_DESC_SMASH";

	public const string RUNE_NAME_WISHFUL = "RUNE_NAME_WISHFUL";

	public const string RUNE_DESC_WISHFUL = "RUNE_DESC_WISHFUL";

	public const string RUNE_NAME_ABUDANCE = "RUNE_NAME_ABUDANCE";

	public const string RUNE_DESC_ABUDANCE = "RUNE_DESC_ABUDANCE";

	public const string DAMAGE_MISS = "DAMAGE_MISS";

	public const string DAMAGE_DODGED = "DAMAGE_DODGED";

	public const string DAMAGE_MIRRORED = "DAMAGE_MIRRORED";
}
