using System;

public static class PlayfabEventId
{
	public static string PRESTIGE_V2 = "PRESTIGE_V2";

	public static string LOOTPACK_OPEN_GEM = "LOOTPACK_OPEN_GEM";

	public static string LOOTPACK_OPEN_FREE = "LOOTPACK_OPEN_FREE";

	public static string FLASH_CURRENCY_OFFER_PURCHASED = "FLASH_CURRENCY_OFFER_PURCHASED";

	public static string FLASH_CHARM_OFFER_PURCHASED = "FLASH_CHARM_OFFER_PURCHASED";

	public static string TRINKET_PURCHASED_GEM = "TRINKET_PURCHASED_GEM";

	public static string TRINKET_DESTROYED = "TRINKET_DESTROYED";

	public static string TRINKET_FORGED = "TRINKET_FORGED";

	public static string HERO_SKIN_PURCHASED = "HERO_SKIN_PURCHASED";

	public static string HERO_ITEM_UPGRADED = "HERO_ITEM_UPGRADED";

	public static string HERO_EVOLVED = "HERO_EVOLVED";

	public static string SHOP_CURRENCY_OFFER_REVEALED = "SHOP_CURRENCY_OFFER_REVEALED";

	public static string SHOP_CURRENCY_OFFER_CHECKOUT = "SHOP_CURRENCY_OFFER_CHECKOUT";

	public static string SHOP_CURRENCY_OFFER_PURCHASE_CLICKED = "SHOP_CURRENCY_OFFER_PURCHASE_CLICKED";

	public static string SHOP_CURRENCY_OFFER_PURCHASED = "SHOP_CURRENCY_OFFER_PURCHASED";

	public static string SHOP_REAL_MONEY_OFFER_REVEALED = "SHOP_REAL_MONEY_OFFER_REVEALED";

	public static string SHOP_REAL_MONEY_OFFER_CHECKOUT = "SHOP_REAL_MONEY_OFFER_CHECKOUT";

	public static string SHOP_REAL_MONEY_OFFER_PURCHASE_CLICKED = "SHOP_REAL_MONEY_PURCHASE_CLICKED";

	public static string SHOP_REAL_MONEY_OFFER_PURCHASED = "SHOP_REAL_MONEY_OFFER_PURCHASED";

	public static string GEM_PACK_PURCHASE = "GEM_PACK_PURCHASE";

	public static string TUTORIAL_STEP_COMPLETE = "TUTORIAL_STEP_COMPLETE";

	public static string TUTORIAL_MISSION_COMPLETED = "TUTORIAL_MISSION_COMPLETED";

	public static string ARTIFACT_EVOLVE = "ARTIFACT_EVOLVE";

	public static string ARTIFACT_SLOT_UNLOCKED = "ARTIFACT_SLOT_UNLOCKED";

	public static string ARTIFACT_REGULAR_CRAFT = "ARTIFACT_REGULAR_CRAFT";

	public static string ARTIFACT_MYTHICAL_CRAFT = "ARTIFACT_MYTHICAL_CRAFT";

	public static string AD_STARTED_DRAGON = "AD_STARTED_DRAGON";

	public static string AD_COLLECTED_DRAGON = "AD_COLLECTED_DRAGON";

	public static string AD_STARTED_SHOP = "AD_STARTED_SHOP";

	public static string AD_COLLECTED_SHOP = "AD_COLLECTED_SHOP";

	public static string TIME_CHALLENGE_COMPLETED = "TIME_CHALLENGE_COMPLETED";

	public static string TIME_CHALLENGE_FAILED = "TIME_CHALLENGE_FAILED";

	public static string GOG_UNLOCKED = "GOG_UNLOCKED";

	public static string GOG_NEW_GATES_DISCOVERED = "GOG_NEW_GATES_DISCOVERED";

	public static string GOG_CURSED_GATE_COMPLETED = "GOG_CURSED_GATE_COMPLETED";

	public static string UPDATE_FORCED_CLICK = "UPDATE_FORCED_CLICK";

	public static string IAP_VALIDATED = "IAP_VALIDATED";

	public static string ATTRIBUTION = "ATTRIBUTION";

	public static string SCREENSHOT_SHARED = "SCREENSHOT_SHARED";

	public static string ACQUIRED_THROUGH_INSTANT = "ACQUIRED_THROUGH_INSTANT";

	public static string SOCIAL_REWARD_COLLECT = "SOCIAL_REWARD_COLLECT";
}
