using System;

namespace Simulation
{
	public enum OfferId
	{
		NONE,
		STARTER_PACK,
		TOKEN_PACK,
		RUNE_PACK,
		CURRENCY_PACK,
		XMAS_PACK,
		FIVE_TRINKETS_PACK,
		THREE_PIJAMA_PACK,
		ONE_TIME_MIDEGAME_GEM_OFFER,
		ONE_TIME_LATEGAME_GEM_OFFER,
		ONE_TIME_PURCHASE_RIFT_OFFER_01,
		ONE_TIME_PURCHASE_RIFT_OFFER_02,
		ONE_TIME_PURCHASE_RIFT_OFFER_03,
		ONE_TIME_PURCHASE_RIFT_OFFER_04,
		ONE_TIME_STAGE_100_OFFER,
		ONE_TIME_STAGE_300_OFFER,
		ONE_TIME_STAGE_800_OFFER,
		REGIONAL_01,
		HALLOWEEN_GEMS,
		CHRISTMAS_GEMS_SMALL,
		CHRISTMAS_GEMS_BIG,
		SECOND_ANNIVERSARY_GEMS,
		SECOND_ANNIVERSARY_CURRENCY_PACK,
		SECOND_ANNIVERSARY_GEMS_TWO,
		SECOND_ANNIVERSARY_CURRENCY_PACK_TWO
	}
}
